config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :actresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/actress.rb
class Actress < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    
    def self.generate_post
        cpz = CrowlCpzServise.new
        page_list = cpz.get_articles
        i = 0
        articles = page_list.map do |p|
            puts "#{i}件目"
            i += 1
            cpz.get_article(p)
            
        end
        
        articles.each do |article|
            post = self.build_post(article)
            post.save!

            article[:dmm_info][:actresses].each do |actress_data|
                actress = Actress.find_or_initialize_by(dmm_id: actress_data[:identifier])
                if actress.new_record?
                    actress[:name] = actress_data[:name]
                    actress.save!
                end
            end
        end
    end

    def self.build_post(article)        
        hash = {
                title: article[:dmm_info][:title],
                description: article[:dmm_info][:description],
                thumbnail_url: article[:dmm_info][:img_url],
                review_score: article[:dmm_info][:review_score],
                service_url: article[:url],
                service_id: article[:service_id],
              }
        Post.new(hash)
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/actresses_controller.rb
class ActressesController < ApplicationController
  before_action :set_actress, only: [:show, :edit, :update, :destroy]

  # GET /actresses
  # GET /actresses.json
  def index
    @actresses = Actress.all
  end

  # GET /actresses/1
  # GET /actresses/1.json
  def show
  end

  # GET /actresses/new
  def new
    @actress = Actress.new
  end

  # GET /actresses/1/edit
  def edit
  end

  # POST /actresses
  # POST /actresses.json
  def create
    @actress = Actress.new(actress_params)

    respond_to do |format|
      if @actress.save
        format.html { redirect_to @actress, notice: 'Actress was successfully created.' }
        format.json { render :show, status: :created, location: @actress }
      else
        format.html { render :new }
        format.json { render json: @actress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actresses/1
  # PATCH/PUT /actresses/1.json
  def update
    respond_to do |format|
      if @actress.update(actress_params)
        format.html { redirect_to @actress, notice: 'Actress was successfully updated.' }
        format.json { render :show, status: :ok, location: @actress }
      else
        format.html { render :edit }
        format.json { render json: @actress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actresses/1
  # DELETE /actresses/1.json
  def destroy
    @actress.destroy
    respond_to do |format|
      format.html { redirect_to actresses_url, notice: 'Actress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actress
      @actress = Actress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actress_params
      params.require(:actress).permit(:name, :initial, :bust, :waist, :hip, :height, :birth, :blood_type, :ruby, :birth_place, :image_lg, :image_sm)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    #before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :thumbnail_url, :review_score, :service_url, :service_id, :ad_url, :series_id, :director_id, :label_id, :maker_id)
    end
end

app/helpers/actresses_helper.rb
module ActressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/actresses/_form.html.haml
= form_for(actress) do |f|
  - if actress.errors.any?
    #error_explanation
      %h2
        = pluralize(actress.errors.count, "error")
        prohibited this actress from being saved:
      %ul
        - actress.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :initial
    = f.text_field :initial
  .field
    = f.label :bust
    = f.number_field :bust
  .field
    = f.label :waist
    = f.number_field :waist
  .field
    = f.label :hip
    = f.number_field :hip
  .field
    = f.label :height
    = f.number_field :height
  .field
    = f.label :birth
    = f.date_select :birth
  .field
    = f.label :blood_type
    = f.text_field :blood_type
  .field
    = f.label :ruby
    = f.text_field :ruby
  .field
    = f.label :birth_place
    = f.text_field :birth_place
  .field
    = f.label :image_lg
    = f.text_field :image_lg
  .field
    = f.label :image_sm
    = f.text_field :image_sm
  .field
    = f.label :sex
    = f.number_field :sex
  .actions
    = f.submit

app/views/actresses/edit.html.haml
%h1 Editing Actress
= render 'form', actress: @actress
= link_to 'Show', @actress
|
= link_to 'Back', actresses_path

app/views/actresses/index.html.haml
%p#notice= notice
%h1 Actresses
%table
  %thead
    %tr
      %th.col-xs-6 Name
      %th Initial
      %th Bust
      %th Waist
      %th Hip
      %th Height
      %th Birth
      %th Blood type
      %th Ruby
      %th Birth place
      %th Image lg
      %th Image sm
      %th{:colspan => "3"}
  %tbody
    - @actresses.each do |actress|
      %tr
        %td.col-xs-6= actress.name
        %td= actress.initial
        %td= actress.bust
        %td= actress.waist
        %td= actress.hip
        %td= actress.height
        %td= actress.birth
        %td= actress.blood_type
        %td= actress.ruby
        %td= actress.birth_place
        %td= actress.image_lg
        %td= actress.image_sm
        %td= link_to 'Show', actress
        %td= link_to 'Edit', edit_actress_path(actress)
        %td= link_to 'Destroy', actress, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Actress', new_actress_path

app/views/actresses/new.html.haml
%h1 New Actress
= render 'form', actress: @actress
= link_to 'Back', actresses_path

app/views/actresses/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @actress.name
%p
  %strong Initial:
  = @actress.initial
%p
  %strong Bust:
  = @actress.bust
%p
  %strong Waist:
  = @actress.waist
%p
  %strong Hip:
  = @actress.hip
%p
  %strong Height:
  = @actress.height
%p
  %strong Birth:
  = @actress.birth
%p
  %strong Blood type:
  = @actress.blood_type
%p
  %strong Ruby:
  = @actress.ruby
%p
  %strong Birth place:
  = @actress.birth_place
%p
  %strong Image lg:
  = @actress.image_lg
%p
  %strong Image sm:
  = @actress.image_sm
%p
  %strong Sex:
  = @actress.sex
%ul
  - @actress.posts.each do | post |
    %li= post.title
= link_to 'Edit', edit_actress_path(@actress)
|
= link_to 'Back', actresses_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Adult
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    - if user_signed_in?
      %p= link_to "ログアウト",destroy_user_session_path , method: :delete

app/views/posts/_form.html.haml
= form_for(post) do |f|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :thumbnail_url
    = f.text_field :thumbnail_url
  .field
    = f.label :review_score
    = f.text_field :review_score
  .field
    = f.label :service_url
    = f.text_field :service_url
  .field
    = f.label :service_id
    = f.number_field :service_id
  .field
    = f.label :ad_url
    = f.text_field :ad_url
  .field
    = f.label :series_id
    = f.number_field :series_id
  .field
    = f.label :director_id
    = f.number_field :director_id
  .field
    = f.label :label_id
    = f.number_field :label_id
  .field
    = f.label :maker_id
    = f.number_field :maker_id
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%p#notice= notice
%h1 Posts
%table
  %thead
    %tr
      %th Title
      %th Description
      %th Thumbnail url
      %th Review score
      %th Service url
      %th Service
      %th Ad url
      %th Series
      %th Director
      %th Label
      %th Maker
      %th{:colspan => "3"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.description
        %td= post.thumbnail_url
        %td= post.review_score
        %td= post.service_url
        %td= post.service_id
        %td= post.ad_url
        %td= post.series_id
        %td= post.director_id
        %td= post.label_id
        %td= post.maker_id
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @post.title
%p
  %strong Description:
  = @post.description
%p
  %strong Thumbnail url:
  = @post.thumbnail_url
%p
  %strong Review score:
  = @post.review_score
%p
  %strong Service url:
  = @post.service_url
%p
  %strong Service:
  = @post.service_id
%p
  %strong Ad url:
  = @post.ad_url
%p
  %strong Series:
  = @post.series_id
%p
  %strong Director:
  = @post.director_id
%p
  %strong Label:
  = @post.label_id
%p
  %strong Maker:
  = @post.maker_id
= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path